-- Move data transcribed from pokewilds-next/battle/moves. Keep the C# values,
-- including current quirks, until a behavior change is made explicitly.
return {
  { id="ancient_power", name="Ancient Power", type="rock", category="special", pp=5,
    effects={{kind="damage", power=40}, {kind="stats", chance=0.1, self=true,
      stages={attack=1, defense=1, sp_attack=1, sp_defense=1, speed=1}}} },
  { id="bind", name="Bind", type="normal", category="physical", pp=20,
    effects={{kind="damage", power=15}, {kind="bind"}} },
  { id="calm_mind", name="Calm Mind", type="psychic", category="status", pp=20,
    target="user", accuracy="always", effects={{kind="stats", stages={sp_attack=1, sp_defense=1}}} },
  { id="confuse_ray", name="Confuse Ray", type="ghost", category="status", pp=10,
    effects={{kind="confuse"}} },
  { id="dive", name="Dive", type="water", category="physical", pp=10,
    effects={{kind="two_turn", semi_invulnerable=true, charge_message="{0} hid underwater!", power=80}} },
  { id="double_edge", name="Double-Edge", type="normal", category="physical", pp=15,
    effects={{kind="damage", power=120, recoil=1/3}} },
  { id="double_kick", name="Double Kick", type="fighting", category="physical", pp=30,
    effects={{kind="multi_hit", power=30, min_hits=2, max_hits=2}} },
  { id="double_team", name="Double Team", type="normal", category="status", pp=15,
    target="user", accuracy="always", effects={{kind="stats", stages={evasion=1}}} },
  { id="dragon_rage", name="Dragon Rage", type="dragon", category="special", pp=10,
    effects={{kind="fixed_damage", amount=40}} },
  { id="draining_kiss", name="Draining Kiss", type="fairy", category="physical", pp=15,
    effects={{kind="damage", power=40, drain=0.75}} },
  { id="fissure", name="Fissure", type="ground", category="physical", pp=5,
    accuracy="ohko", effects={{kind="ohko"}} },
  { id="headbutt", name="Headbutt", type="normal", category="physical", pp=15,
    effects={{kind="damage", power=70}, {kind="flinch", chance=0.3}} },
  { id="night_shade", name="Night Shade", type="ghost", category="special", pp=15,
    effects={{kind="level_damage"}} },
  { id="petal_dance", name="Petal Dance", type="grass", category="special", pp=10,
    effects={{kind="consecutive", power=10, min_turns=2, max_turns=3, confuse_after=true}} },
  { id="pin_missile", name="Pin Missile", type="bug", category="physical", pp=20, accuracy=0.95,
    effects={{kind="multi_hit", power=25, min_hits=2, max_hits=4}} },
  { id="poison_sting", name="Poison Sting", type="poison", category="physical", pp=35,
    effects={{kind="damage", power=15}, {kind="status", status="poisoned", chance=0.3}} },
  { id="protect", name="Protect", type="normal", category="status", pp=10,
    target="user", priority=4, effects={{kind="protect"}} },
  { id="recover", name="Recover", type="normal", category="status", pp=5,
    target="user", accuracy="always", fail_on_full_hp=true, effects={{kind="heal", fraction=0.5}} },
  { id="rest", name="Rest", type="psychic", category="status", pp=5,
    target="user", accuracy="always", fail_on_full_hp=true,
    effects={{kind="status", status="asleep_rest", replace=true}, {kind="heal", fraction=1, hide_message=true}} },
  { id="rollout", name="Rollout", type="rock", category="physical", pp=20, accuracy=0.9,
    effects={{kind="consecutive", power=30, min_turns=5, max_turns=5, double_power=true}} },
  { id="sandstorm", name="Sandstorm", type="rock", category="status", pp=10,
    target="field", effects={{kind="weather", weather="sandstorm", turns=5}} },
  { id="shadow_claw", name="Shadow Claw", type="ghost", category="physical", pp=15,
    effects={{kind="damage", power=70, high_crit=true}} },
  { id="solar_beam", name="Solar Beam", type="grass", category="special", pp=10,
    effects={{kind="two_turn", power=120, charge_message="{0} took in sunlight!", skip_in_sun=true}} },
  { id="splash", name="Splash", type="normal", category="physical", pp=20,
    effects={{kind="splash"}} },
  { id="storm_throw", name="Storm Throw", type="fighting", category="physical", pp=10,
    effects={{kind="damage", power=60, always_crit=true}} },
  { id="sunny_day", name="Sunny Day", type="fire", category="status", pp=5,
    target="field", effects={{kind="weather", weather="sun", turns=5}} },
  { id="swagger", name="Swagger", type="normal", category="status", pp=15, accuracy=0.85,
    effects={{kind="stats", stages={attack=2}}} },
  { id="tackle", name="Tackle", type="normal", category="physical", pp=35, accuracy=0.95,
    effects={{kind="damage", power=40}} },
  { id="toxic", name="Toxic", type="poison", category="status", pp=10, accuracy=0.9,
    effects={{kind="status", status="badly_poisoned"}} },
}
